// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Game struct {
	ID          string
	WhitePlayer string
	BlackPlayer string
	Result      sql.NullInt64
}
